export enum AdminPaymentTableHeaders {
    DAY_DELIVERED = 'Day Delivered',
    ORDER_ID = 'Order Id',
    SUB_ORDER_ID = 'SubOrder ID',
    MERCHANT = 'MERCHANT',
    RUC = 'RUC',
    STORE = 'TIENDA',
    COUPON = 'Coupon',
    MONTO_COUPON = 'Monto Cupon',
    TIPO_SHIPPING = 'Tipo Shipping',
    MONTO_SHIPPING = 'Monto Shipping',
    COMISION = '% Comisión',
    MONTO_COMISION = 'Monto Comisión S/',
    NMV = 'NMV S/',
}
